version: "3"
services:
  app:
    container_name: app
    restart: always
    environment:
      - NODE_ENV=production
    build: ./
    ports:
      - "80:80"
      - "8080:8080"
      - "9229:9229"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:7.0.3
    volumes:
      - ~/Diagnostic-Tool-Data:/data/db
    ports:
      - "27017:27017"
